# Travis CI setup for swak4Foam-dev
# https://openfoamwiki.net/index.php/Installation/swak4Foam/Installing_On/Ubuntu#Ubuntu_10.04_to_14.10

sudo: required
dist: trusty
language: cpp

env:
  global:
    - REPO_DIR=$PWD

before_install:
    - sudo apt-get install -qq git-core build-essential binutils-dev cmake flex bison zlib1g-dev qt4-dev-tools libqt4-dev libqtwebkit-dev gnuplot libreadline-dev libncurses-dev libxt-dev libopenmpi-dev openmpi-bin libboost-system-dev libboost-thread-dev libgmp-dev libmpfr-dev python python-dev
    - mkdir ~/OpenFOAM

install:
    - cd ~/OpenFOAM
    - git clone https://github.com/OpenFOAM/OpenFOAM-dev.git
    - git clone https://github.com/OpenFOAM/ThirdParty-dev.git
    - source $HOME/OpenFOAM/OpenFOAM-dev/etc/bashrc
    # Obtain binaries built by wyldckat
    - wget https://github.com/wyldckat/OpenFOAM-dev/releases/download/20160227-181109/OpenFOAM-dev.linux64GccDPInt32Opt_2016-02-27.tbz
    - tar -xf OpenFOAM-dev.linux64GccDPInt32Opt_2016-02-27.tbz
    - wget https://github.com/wyldckat/ThirdParty-dev/releases/download/20160227-181109/ThirdParty-dev.linux64GccDPInt32Opt_2016-02-27.tbz
    - tar -xf ThirdParty-dev.linux64GccDPInt32Opt_2016-02-27.tbz
    # Check that we have OpenFOAM installed
    - icoFoam -help
    # Move swak4Foam repo into the correct directory
    - cd ~
    - mkdir -p $WM_PROJECT_USER_DIR
    - mv $REPO_DIR $WM_PROJECT_USER_DIR/swak4Foam-dev

before_script:
    - source $HOME/OpenFOAM/OpenFOAM-dev/etc/bashrc
    - cd $WM_PROJECT_USER_DIR/swak4Foam-dev

script:
    - ./maintainanceScripts/compileRequirements.sh
    - ./Allwmake
