# Travis CI setup for swak4Foam-dev
# https://openfoamwiki.net/index.php/Installation/swak4Foam/Installing_On/Ubuntu#Ubuntu_10.04_to_14.10

sudo: required
dist: trusty
language: cpp

env:
    global:
        - REPO_DIR=$PWD
    matrix:
        # Build against latest OpenFOAM 3.0 deb pack
        - OF_VERSION="3.0" OF_RC=/opt/openfoam30/etc/bashrc
        # Build against OpenFOAM-dev
        - OF_VERSION="dev" OF_RC=$HOME/OpenFOAM/OpenFOAM-dev/etc/bashrc

before_install:
    - sudo apt-get install -qq git-core build-essential binutils-dev cmake flex bison zlib1g-dev qt4-dev-tools libqt4-dev libqtwebkit-dev gnuplot libreadline-dev libncurses-dev libxt-dev libopenmpi-dev openmpi-bin libboost-system-dev libboost-thread-dev libgmp-dev libmpfr-dev python python-dev
    - mkdir ~/OpenFOAM

install:
    - ./ci/installOF.sh $OF_VERSION

before_script:
    - source $OF_RC
    # Move swak4Foam repo into the correct directory
    - cd ~
    - mkdir -p $WM_PROJECT_USER_DIR
    - mv $REPO_DIR $WM_PROJECT_USER_DIR/swak4Foam-dev

script:
    - cd $WM_PROJECT_USER_DIR/swak4Foam-dev
    - ./maintainanceScripts/compileRequirements.sh
    - ./Allwmake
